### PR TITLE
Merge `prepare_regions.sh` script commits from dev branch

### PR DESCRIPTION
**Pull request by youngchanpark**
Hi, 
I wanted to merge a single file, but the dev branch has a lot of other changes too so I wanted to make it simple so made a separate branch for this PR.

I included all the latest commits for `prepare_regions.sh` script in the dev branch except for the very last commit. 

The very last commit added the axelq(-q) option, but this was causing an error because of the definition of an empty variable `axelq=''`passed onto axel command makes the axel command not download the given url.

Example:
```
axel -a https://storage.googleapis.com/gtex_analysis_v8/single_tissue_qtl_data/GTEx_Analysis_v8_eQTL.tar
# This downloads

axelq=''
axel "$axelq" -a https://storage.googleapis.com/gtex_analysis_v8/single_tissue_qtl_data/GTEx_Analysis_v8_eQTL.tar
# This doesn't download

axelq="-q"
axel "$axelq" -a https://storage.googleapis.com/gtex_analysis_v8/single_tissue_qtl_data/GTEx_Analysis_v8_eQTL.tar
# This downloads
```

So I tested the `prepare_regions.sh` script up to just before the axelq commit like below. 
```
cd ~young-chan.park/repos
git clone https://github.com/hmgu-itg/burden_testing.git
mv burden_testing burden_testing_rollback_axelq

cd burden_testing_rollback_axelq
git checkout 3aa16fd -- prepare_regions.sh

./prepare-regions -o ~young-chan.park/burden-regions-rolledback-axelq-rerun
```
Output
```
...
Downloading cell type : hepatocyte
Downloading cell type : iPS_15b
Downloading cell type : iPS_20b
Downloading cell type : iPS_DF_19_11
Downloading cell type : iPS_DF_6_9
Downloading cell type : keratinocyte
Downloading cell type : kidney
Downloading cell type : large_intestine
[Error] At this step something failed. The file was not created! /home/itg/young-chan.park/burden-regions-rolledback-axelq-rerun/prepare_regions_tempfiles/2021.05.06/EnsemblRegulation/large_intestine.gff.gz
[Error] Exiting.
```

This run ran till the `===== REGULATION =====` part. 

It seems to have failed due to a temporary network failure.  

Rerun with the `-r (reuse)` option successfully completed till the end.
```bash

cd ~/repos/burden_testing_rollback_axelq

./prepare-regions -r -o ~/burden-regions-rolledback-axelq-rerun 2>&1 | tee ~young-chan.park/burden-regions-rolledback-axelq-rerun.2.oe

# Check output.
tail ~young-chan.park/burden-regions-rolledback-axelq-rerun.2.oe
```
Output of `tail`
```
[Info 12:22] Output file was saved as: Linked_features.bed.gz

[Info 12:22] Total number of lines in the final files: 4360102

[Info 12:22] Number of lost associations: 8712, belonging to 307 genes in the following sources: GTEx


[Info 12:22] The End
```

`cat ~young-chan.park/burden-regions-rolledback-axelq-rerun/config.txt`
```
VEPdir=/home/itg/young-chan.park/burden-regions-rolledback-axelq-rerun/vep
VEPexec=/home/itg/young-chan.park/burden-regions-rolledback-axelq-rerun/ensembl-vep/vep
EigenPath=/home/itg/young-chan.park/burden-regions-rolledback-axelq-rerun/scores/eigen.phred_v2.dat
caddPath=/home/itg/young-chan.park/burden-regions-rolledback-axelq-rerun/scores/whole_genome_SNVs.tsv.gz
Linked_features=/home/itg/young-chan.park/burden-regions-rolledback-axelq-rerun/Linked_features.bed.gz
gencode_file=/home/itg/young-chan.park/burden-regions-rolledback-axelq-rerun/gencode.basic.annotation.tsv.gz
```

### CODE REVIEW

**Comment by youngchanpark** [comment]
Hi @agilly and @andrei-barysenka,

Sorry for the flattened commit history. I tried finding a git command that would pull changes for just one file from the dev branch to this branch `update_prepare_regions` whilst also preserving the history, but couldn't find it. 

If you know of a way, I'd appreciate it if you could show me. I'll reopen the PR with the preserved history if possible.

**Review by agilly — APPROVED** [review]
seems all right, provided that Andrei's changes after Jan 20, are tested.

**Comment by andrei-barysenka** [comment]
OK, seems fine

**Review by andrei-barysenka — COMMENTED** [review]
seems fine

**Comment by youngchanpark** [comment]
Reopening PR because Andrei reviewed and said its fine, but accidentally closed the PR.

**Pull request merged**
